-- Fix search_key records that contain đ (generated by buggy JS normalizeSearchText)
-- The JS normalizeSearchText used NFD + strip combining marks, which preserves đ/Đ
-- because D-with-stroke (U+0111/U+0110) does not decompose in NFD.
-- PostgreSQL translate() correctly maps đ → d, Đ → d.

update public.han_characters
set search_key = lower(translate(
  coalesce(character, '') || ' ' || coalesce(han_viet, ''),
  'àáảãạăắằẳẵặâấầẩẫậèéẻẽẹêếềểễệìíỉĩịòóỏõọôốồổỗộơớờởỡợùúủũụưứừữửựỳýỷỹỵđÀÁẢÃẠĂẮẰẲẴẶÂẤẦẨẪẬÈÉẺẼẸÊẾỀỂỄỆÌÍỈĨỊÒÓỎÕỌÔỐỒỔỖỘƠỚỜỞỠỢÙÚỦŨỤƯỨỪỬỮỰỲÝỶỸỴĐ',
  'aaaaaaaaaaaaaaaaadeeeeeeeeeeeiiiiiooooooooooooooooouuuuuuuuuuuyyyyydaaaaaaaaaaaaaaaaadeeeeeeeeeeeiiiiiooooooooooooooooouuuuuuuuuuuyyyyyd'
))
where search_key ~ 'đ';

comment on column public.han_characters.search_key is
  'Normalized concatenation of character and han_viet for accent-insensitive lookup (fixed đ→d)';
